### ISSUE TITLE
Cache expiration mechanism

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#12]
Normally cached files must be stored for a limited period of time. A mechanism should be created for making sure files will be purged from the storage after their expiration time have been reached.

Ideally, all cache modules should be able to share the same cache expiration code. If this proves to be impossible we will have to implement it in every cache module individually.

For the moment I am thinking of a type which only job is to keep track of expiration times and emit expiration events when such a time is reached.

**Comment by MStoykov** [comment]
I remember [time.Timer](http://golang.org/pkg/time/#Timer) was pretty efficient. A tiny little bit of wrapping should be enough ?

**Comment by ironsmile** [comment]
I can't think of a way to do it with a simple wrapper. We will have to keep track of thousands of files. Millions, possibly.

I am thinking of a heap with expiration times. Whenever a file is added or removed from the cache the heap will be changed as well. And there will be a goroutine which starts a time.Timer for the top of the heap. When the timer expires it removes the file from the cache. The starts a timer for the next time in the heap and repeats.
