### ISSUE TITLE
New handler: rewrite request headers

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#124]
A module for adding, editing or removing request headers. With this module we should be able to configure headers for different vhosts or locations. I am thinking for interface like this:

```
"virtual_hosts": {

  "localhost": {

    "remove_headers": ["Accept-Encoding"],

    "add_headers": {
      "Cookie": "injected=really"
    },

    "locations": {
      "set_headers": {
        "Accept": "application/json"
      }
    }

  }

}
```

We should have the following directives:

* `remove_header` - removes the header(s) with this name from the `http.Request`
* `add_header` - adds this header to the `http.Request` headers even if there is a header with the same name already
* `set_header` - sets the header to this value and removes all other headers with the same name.

This handler will be perfect for rewriting requests in a way other handlers in the chain can use.

**Comment by MStoykov** [comment]
fixed in e20588d
