### ISSUE TITLE
Config test does not report an error on missing upstream key

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#128]
The following config has an error:

```
    "http": {
        "default_handlers": [
            {
                "type" : "cache"
            },
            {
                "type" : "proxy"
            }
        ],

        "virtual_hosts": {

            "127.0.0.6": {
                "cache_zone": "zone2",
                "cache_key": "7.4"
            }

        }
```

The virtual host "127.0.0.6" is using the proxy handler as its last handler. But does not define an upstream address. Nevertheless `nedomi -t` does not report any error. It should report "No upstream address for proxy handler in 127.0.0.6", just as actually trying to start the server with the above config does.

**Comment by MStoykov** [comment]
this is because the error is returned in the "constructor" of the handler and the construction of the handlers does not happen when the '-t' flag is provided.

**Comment by na--** [comment]
This will be very difficult and ugly to implement with the current configuration, we can fix it when we refactor the config. A similar problem is that the settings `cache_zone` and `cache_key are relevant only for the `cache` handler and should be checked by it.
