### ISSUE TITLE
Configuration reloading

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#129]
We must be able to reload the web server configuration often. For example, adding vhost or cache zone must not be an "event". It should happen seamlessly and possibly, few times per minute.

At the moment `nedomi` kind of [supports reloading configuration](https://github.com/ironsmile/nedomi/blob/master/app/app.go#L131). I do not believe it is working at all in its current state.

In order to make repetitive reloading possible we must reuse as much of the already constructed objects as possible:

* The cache algorithm
* Upstream objects
* Storage objects
* Already opened listening sockets

There is one thing which I would consider a necessary exceptions to the rule of preserving already used resources. The log files should be opened anew on reload. This will make possible rotating the server log with OS tools such as logrotate.

Obviously, we shouldn't drop any connections/requests during reload.

**Comment by MStoykov** [comment]
Should this be closed?

**Comment by ironsmile** [comment]
Yes, I think so.
