### ISSUE TITLE
Release branches, change logs and reproducible builds

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#146]
We have to start creating release branches. For example `release/0.1`, `release/0.2` etc. This is the only way we can support more than one released version at a time. There are few things we have to take into consideration, though.

* When is the point when we call something "a release" and branch it out?
* We have to have some kind of convention on release numbering.
* How long do we "support" an release?
* What is the version of the master branch?

On top of that, a proper change log should be maintained between releases. It is really important for anyone trying to use the software and keep it up to date for any considerable amount of time.

Lastly, building a "release" must be reproducible once the release is created. For that end we must vendor all of our dependencies one way or another. Changes in an external project should not break older, but still supported release of nedomi.

**Comment by MStoykov** [comment]
maybe use version as per [the release proposal](https://github.com/golang/proposal/blob/master/design/12302-release-proposal.md)?

**Comment by ironsmile** [comment]
:+1:

**Comment by ironsmile** [comment]
Well, I went ahead and created branch [release/0.1](https://github.com/ironsmile/nedomi/tree/release/0.1) from which I tagged the first release, [v0.1.0](https://github.com/ironsmile/nedomi/releases/tag/v0.1.0). All further 0.1.x releases will be tagged from this branch.

The next steps are creating a change log and vendoring our dependencies into this branch. @MStoykov is researching which vendoring tool will suit us the most. At the moment our approach is to vendor only in the release branches using a [go1.5-compatible](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit) vendoring tool while keeping `master` clean of any of it.

**Comment by MStoykov** [comment]
I propose that we use [govendor](https://github.com/kardianos/govendor).

It does the job of copying all the currently used external dependencies inside `vendor` directory from the current GOPATH. Writing a `vendor/vendor.json` file which tells what the revision of the packages were at the time of adding them.  

It doesn't allow for uncommitted trees to be vendored which means that it would be hard (never impossible) to vendor uncommitted external code. This of course can't check whether the code has been pushed.
 There is also currently no check that the code that is vendored is the same as any external version. 
You can't specify what version you want in the `vendor/vendor.json` file, but you can checkout that version inside your current GOPATH and then `govendor update <import path>`. 

The proposed process of development will be to not actually use govendor up to the time when a new version will be released. Then when the branch for it is made the person/script making the release will checkout (or not) the external packages to desired versions and run 

```shell
govendor init # just init
govendor list +external #list all the packages which will be 
#vendored so that some specific version could be checkout if wanted
govendor update +external # install all external packages
git add vendor
git commit -m "vendor packages before release/vX.Y.Z"
```

This way while development we can go as usual without actually worrying that some tool or another doesn't have proper support for vendor experiment. 

The main downside is that the person doing the release has to update (or not) their dependencies manually and no auto updating of them is currently supported.

**Comment by ironsmile** [comment]
I've adopted @MStoykov's solution for vendoring in the release/0.1. `GO15VENDOREXPERIMENT=1` is added in the Makefile.
