### ISSUE TITLE
Config test: no error on missing cache zone directory

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#167]
If in the config file a cache zone is configured with a directory which does not exist nedomi wouldn't start and spew "directory does not exist" which is fine. But if you execute the config test with `nedomi -t -c config.json` no such error is shown. This results in situations such as this:

```
you: nedomi, is this config ok?
nedomi: yes!
you: ok, start with it then.
nedomi: ouuu, the config is not ok! Change it.
you: :'(
```

Jokes aside, this is an issue. When you try to upgrade (`kill -USR2`) a nedomi binary with new one the above behaviour is the reason for an unsuccessful operation and a lingering zombie process.

**Comment by MStoykov** [comment]
closed with db6e96dbd9930f65f2d34aaf1919aca34615bf07 , but I forgot the '#' in commit message ... sorry.
