### ISSUE TITLE
Replace go generate bash scripts and templates with go run and go templates

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#19]
Throughout our modules we use `go generate` to find and generate go code for all modules. At the moment this is done via bash script and partial templates. The templates are in different files like `template.0`, `template.1` and so on.

It would be a better idea to make this bash script a go "script" which will be run with

```
//go:generate go run ./script.go
```

And instead of separate files we can have a go `text/template`.

**Comment by ironsmile** [comment]
I tested the "bashless" method in generating the upstream modules and it works great! The next step is to convert the old modules into this new system. It is much easier to read and understand. Also, removes the bash dependency so that windows devs wouldn't have to worry about it!

**Comment by MStoykov** [comment]
Looks good, although I would prefer if adding the script is one commit and making upstream module based another. As well as all the unrelated changes to not be in the branch.

I also wonder if it won't be better if it's outside the project as a separate one and then put in the README that `go get github.com/ironsmile/module_generator` should be ran before `go generate`.

**Comment by ironsmile** [comment]
Yes, the commit was too big!

About the module generator. I would rather keep it in this repo. This way we can keep it self contained. In case it grows any further we can think about it again. For now my feeling is that the less dependencies the better.
