### ISSUE TITLE
Request ID

### ISSUE THREAD

**Issue by MStoykov** [ironsmile/nedomi#191]
Currently in a lot of places we write the address of the handler currently processing the request. 
This has downsides:
1. no easy and consistent way to trace request between different handlers
2. the address are heavily reused

because of this I propose each request to have it's own ID. that is given to it when the request is accepted in app/net.go. This id can than be put inside the context and used where ever needed.

This raises some additional questions: 
* Should the id be just a (unique) number or should it be something that has meaningful information? 
* Should there be size limitation on the id and if yes, what?
* If the id is just a number, should when it's created, some meaningful information to be logged about the request?
* Some handlers(mp4/flv) have to make additional new requests. It will be nice to have their own unique ids. Also it will be better if they are related to the original one.
* Should any of this be configurable

*Meaningful Information* is understood non exclusively to include: 
* the url that is requested
* some headers(mostly the Host one) 
* the time of the request
* the remote address

**Comment by MStoykov** [comment]
My proposition is: 
* just a number in the app/net.go generated from a counter and some instance specific information, hashed/prefixed id of sorts.
* size limitation of around 20 characters: if the id is hexed that is 655,360,000,000,000,000,000 this is more than 2^64 which is fine, unique for until a 64bit int loops is good enough for me :)
* the id with some meaningful information is logged - the accesslog includes it as well, or just the accesslog depending on what information is logged 
* the id is appended and we hope that no handler chain with a bunch of id adding is used.
* the server id, maybe the size of the request id as well as what information is logged at request id creation

**Comment by ironsmile** [comment]
:+1: 
I think it would be a great idea to add it in the response headers as an `X-*` header. Maybe `X-RID`. This maybe configurable as well. In some situations we may want it, in others - not.
