### ISSUE TITLE
Support for additional modules

### ISSUE THREAD

**Issue by MStoykov** [ironsmile/nedomi#194]
Currently if someone decides to write their own modules they can do it and just put them in a directory for the given module. 
But running `go generate` will change `types.go` in order for the modules to be imported and useful. This means that it will be harder to do other changes and not accidentally commit `types.go`. 

I propose that we add the possibility for the module_generator to inspect a predefined gitignored file, `additional.list`, with list of package names to be included in `additional_types.go`.

Illustrating example: 
>
> inside module_dir/additional.list:
> ```go
> example.com/modules/awesome
> example.com/modules/super
> ```
> 
> inside module_dir/new.go
> ```go
> // module_dir documentation
> package module_dir
> 
> //go:generate go run ../tools/module_generator/main.go -template "types.go.template" -output  "types.go"
>
> //go:generate go run ../tools/module_generator/main.go -inputlist additional.list -template "additional_types.go.template" -output "additional_types.go"
> ```

* will give all the sub directories inside `module_dir` to `types.go.template` as arguments
* will give the contents of `additional.list` to `additional_types.go.template` as arguments

This means that the changes will be to the:
* module_generator
* all `new.go` files
* new templates `additional_types.go.template`
* .gitignore (adding `additional.list`, `additional_types.go`)
* maybe rewrite the `types.go.template` and move everything, but adding to the map, in `new.go`

**Comment by ironsmile** [comment]
The example for `go:generate` comments is slightly wrong. It contains `-output > "types.go"` which, I think, is wrong.

**Comment by MStoykov** [comment]
yes - i fixed it

**Comment by MStoykov** [comment]
if the inputlist is empty file or missing, `go generate` will have to just log it without actually failing.
