### ISSUE TITLE
Dir handler: root directory is not rooted

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#208]
Lets say, the `dir` handler is used and its root is configured to be `/var/www/app`. One would expect the file `/var/www/app/index.html` to be accessible at the web path '/index.html'. This is not the case. In such a configuration, the file will not be found at this path. It is not clear what exactly does the root directory mean.

**Comment by MStoykov** [comment]
Seems to work. 

What doesn't (and is probably what the issue is) is that if you have location let's say '/somewhere/else' which has `dir` handler with root `/var/www` accessing `/somewhere/else/index.html` will try to get `/var/www/somewhere/else/index.html`.

**Comment by MStoykov** [comment]
#218 will fix is a solution to the problem I described in the previous comment

**Comment by ironsmile** [comment]
Yes, the propsed solution can solve the problem. I find it unituitive but it will do.
