### ISSUE TITLE
Source of HTTP error messages (eg. "404 page not found")

### ISSUE THREAD

**Issue by alectrocute** [ironsmile/nedomi#228]
Hey @ironsmile,

I'm going to be annoying, I already feel bad.

I've combed through this code for hours and couldn't find where the error messages are originating from, eg. "404 page not found". I've looked through the dependencies as well to no avail.

If I'd like to change the error message to a custom one, such as setting http.NotFound to say "This page isn't available", etc. where would I go about doing that?

Thanks so much!

**Comment by ironsmile** [comment]
Hello @alectrocute ! This probably comes from the [NotFound handler](https://golang.org/pkg/net/http/#NotFound) in the standard http library. Here is its source where the [message is sent](https://golang.org/src/net/http/server.go?s=61615:61658#L2002).

As far as I can tell you are using [the dir handler](https://github.com/ironsmile/nedomi/blob/62dd75e41ad1eb8996a63dfe87674d61fa3beb13/handler/dir/dir.go) which itself uses [http.FileServer](https://golang.org/pkg/net/http/#FileServer).

Being able to change the "not found" page would be great. Or any other error page, similar to the [error_page](https://nginx.org/en/docs/http/ngx_http_core_module.html#error_page) directive in nginx. I don't think we have this feature in `nedomi` at this moment. You can modify the dir handler or alternatively write a new handler which supports internal redirects for error pages. There is [this guide](https://github.com/ironsmile/nedomi/blob/master/handler/README.md) for writing new handlers.
