### ISSUE TITLE
Fix possible write in a closed channel

### ISSUE THREAD

**Issue by na--** [ironsmile/nedomi#32]
[TieredLRUCache.remove()](https://github.com/ironsmile/nedomi/blob/59b4845bb8898fb91b374a05beb8b5be27c01b79/cache/lru/lru.go#L154) may write in a closed channel if [app.Stop() or app.Reload()](https://github.com/ironsmile/nedomi/blob/59b4845bb8898fb91b374a05beb8b5be27c01b79/app/app.go#L283) was called.

Probably, the cache modules should be responsible for closing the remove channels themselves.

**Comment by MStoykov** [comment]
This is fixed after aa818f0 ?

**Comment by na--** [comment]
Yes
