### ISSUE TITLE
Optimize downloads from upstream

### ISSUE THREAD

**Issue by na--** [ironsmile/nedomi#44]
At the moment, if a client makes a HTTP request to nedomi for a file that we have not cached, nedomi will make 1 HTTP HEAD request to the upstream for the headers and then one or many HTTP GET requests to the upstream for all the pieces of the file. The number of GET requests depends on the file size or requested range, but it can be a big number for large files. This should be optimized, probably after we complete #43.

**Comment by MStoykov** [comment]
The situation in which some amount of the file has already been cached - 80 out of 100 pieces?
