### ISSUE TITLE
Remove the VirtualHost's CacheAlgorithm

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#48]
As far as I can tell the [CacheAlgorithm property](https://github.com/ironsmile/nedomi/blob/3e4fd0af0a17a84de142fe0a1784071b7814a340/vhost/virtual_host.go#L14) is never actually used. So it may be safely removed. I just want to use the opportunity to use [go oracle](https://godoc.org/golang.org/x/tools/cmd/oracle) to verify my judgement.

**Comment by na--** [comment]
Can we close this?

**Comment by MStoykov** [comment]
closed by 1f758f0
