### ISSUE TITLE
Storage.disk restore from disk is blocking

### ISSUE THREAD

**Issue by MStoykov** [ironsmile/nedomi#56]
Storage.disk.New blocks until it restores from disk - which may take hours.
In order for nedomi to be responsive and start serving requests, the restore should run in the background. 
Needed changes indetified so far: 
- Storage.disk should stat ObjectIndex-es that are supposevely missing(atleast while restore is running).
- Restore should be throttleable as to not slow down nedomi too much. 
- Some logistics about when nedomi is under load in order to throttle the restoring (probably other less important task in the future).
- Deal with the fact that this will enable the storage to store more data than it is configured to (possibly a lot more).

**Comment by na--** [comment]
This is finished, only some polishing, configurability and testing remain. Leaving it open for now, will close it after I'm satisfied it's working as intended.

**Comment by MStoykov** [comment]
was closed with 4975ec2
