### ISSUE TITLE
Separation between debug, info and error logs

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#8]
At the moment logging in the server is ad-hoc. All is written in a single file and there is no way to separate the important logs from the rest. We should have some way of saying "this is a debug log" when printing and a configuration which tells what kind of logs should be emitted and where.

I propose separating the logs in three levels: debug, info and error. We should be able to turn on and off all levels. With something like that in the config:

```
    "logging": {
        "log_file": "/tmp/example.log",
        "level": "debug"
    }
```

where *level* can be "no_log", "debug", "info" and "error". Setting it to "debug" level will print everything, "info" will print info and error logs and "error" will print only error logs. The special "no_log" will make sure no logs are emitted.

The default logging module in the standard's library is very limited and something else should be use. For example: [my lib for logging](https://github.com/ironsmile/logger). It is up for the task described here.

**Comment by MStoykov** [comment]
Should we have per module logs? 
Maybe something like an application Wide log and then overriding this in each module if required. 
It will be beneficial to have debug log enabled only for one or two modules and not everything.

**Comment by ironsmile** [comment]
Yes! Great idea. Every module must be able to have its logging level configured separately.
