### ISSUE TITLE
Virtual Host Aliases

### ISSUE THREAD

**Issue by ironsmile** [ironsmile/nedomi#86]
We must be able to have multiple domains for particular virtual host. One possible way to do this is by "aliases". Basically, something similar to the apache's [ServerAlias](https://httpd.apache.org/docs/2.2/mod/core.html#ServerAlias).

This is my proposition for configuration:

```json
"cached.example.com": {
    "aliases": [
        "first.example.com",
        "second.other.com",
        "third.wow.com"
    ],
    "upstream_address": "http://localhost",
    "cache_zone": "zone2",
    "cache_key": "1.2"
}
```

I will try to hack an implementation of this idea and create a pull request.

**Comment by MStoykov** [comment]
:+1:
